plugins {
    id 'com.android.application'
}

android {
    namespace 'com.timecool.app'
    compileSdk 34

    defaultConfig {
        applicationId "com.timecool.app"
        minSdk 26
        targetSdk 34
        versionCode 1
        versionName "2.0"
    }

    buildTypes {
        debug {
            debuggable true
            applicationIdSuffix ".debug"
            versionNameSuffix "-debug"
        }
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

dependencies {
}
